-- MySQL Script generated by MySQL Workbench
-- 05/14/15 20:54:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TP_ACESSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TP_ACESSO` (
  `ID_TP_ACESSO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_TP_ACESSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TP_PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TP_PESSOA` (
  `ID_TP` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `NOME` VARCHAR(150) NOT NULL,
  `CPF_CNPJ` VARCHAR(15) NOT NULL,
  `E_MAIL` VARCHAR(150) NOT NULL,
  `SEXO` CHAR(1) NULL,
  `TELEFONE` VARCHAR(9) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `RUA` VARCHAR(45) NOT NULL,
  `BAIRRO` VARCHAR(45) NULL,
  `NUMERO` VARCHAR(45) NOT NULL,
  `LOGIN` VARCHAR(20) NOT NULL,
  `SENHA` VARCHAR(10) NOT NULL,
  `TP_ACESSO_ID_TP_ACESSO` INT NOT NULL,
  `TP_PESSOA_ID_TP` INT NOT NULL,
  PRIMARY KEY (`CPF_CNPJ`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `LOGIN_UNIQUE` ON `mydb`.`USUARIO` (`LOGIN` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`NACIONALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NACIONALIDADE` (
  `ID_NACIONALIDADE` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_NACIONALIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AUTOR` (
  `ID_AUTOR` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `SOBRENOME` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(150) NULL,
  `CPF` VARCHAR(11) NULL,
  `SEXO` CHAR(1) NULL,
  `E-MAIL` VARCHAR(45) NOT NULL,
  `IDADE` INT(3) NULL,
  `NACIONALIDADE_ID_NACIONALIDADE` INT NOT NULL,
  `DESCRICAO` VARCHAR(450) NULL,
  PRIMARY KEY (`ID_AUTOR`, `NACIONALIDADE_ID_NACIONALIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GENERO` (
  `ID_GENERO` INT NOT NULL,
  `DESCRIÇÃO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_GENERO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `ID_CATEGORIA` INT NOT NULL,
  `DESCRIÇÃO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_CATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDITORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDITORA` (
  `ID_EDITORA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `E-MAIL` VARCHAR(200) NOT NULL,
  `TELEFONE` VARCHAR(9) NOT NULL,
  `CONTATO` VARCHAR(90) NOT NULL,
  `CNPJ` VARCHAR(12) NOT NULL,
  `IE` VARCHAR(45) NULL,
  `SITE` VARCHAR(150) NULL,
  `TIPO` VARCHAR(30) NULL,
  `RAZÃO SOCIAL` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID_EDITORA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROMOÇÃO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROMOÇÃO` (
  `DATA_INICIO` DATE NOT NULL,
  `DATA_FIM` DATE NOT NULL,
  `VALOR_DESCONTO` FLOAT NOT NULL,
  `ID_PROMOÇÃO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_PROMOÇÃO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMENTARIO` (
  `ID_COMENTARIO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(450) NOT NULL,
  `DATA_HORA` DATETIME NOT NULL,
  `USUARIO_CPF_CNPJ` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_COMENTARIO`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Id_Comentario_UNIQUE` ON `mydb`.`COMENTARIO` (`ID_COMENTARIO` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`LIVRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIVRO` (
  `ID_LIVRO` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(100) NOT NULL,
  `VALOR` FLOAT(8,2) NOT NULL,
  `ISBN` INT NOT NULL,
  `NUMERO DE PAGINA` INT NOT NULL,
  `ANO` YEAR NOT NULL,
  `IDIOMA` VARCHAR(45) NULL,
  `DESCRIÇÃO` VARCHAR(300) NOT NULL,
  `AUTOR_ID_AUTOR` INT NOT NULL,
  `CATEGORIA_ID_CATEGORIA` INT NOT NULL,
  `EDITORA_ID_EDITORA` INT NOT NULL,
  `GENERO_ID_GENERO` INT NOT NULL,
  `PROMOÇÃO_ID_PROMOÇÃO` INT NOT NULL,
  `COMENTARIO_ID_COMENTARIO` INT NOT NULL,
  PRIMARY KEY (`ID_LIVRO`, `COMENTARIO_ID_COMENTARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CARRINHO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARRINHO` (
  `ID_CARRINHO` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_CPF_CNPJ` INT NOT NULL,
  `LIVRO_ID_LIVRO` INT NOT NULL,
  PRIMARY KEY (`ID_CARRINHO`, `USUARIO_CPF_CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LISTA DE DESEJOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LISTA DE DESEJOS` (
  `ID_LISTA` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA` DATETIME NULL,
  `LIVRO_ID_LIVRO` INT NOT NULL,
  PRIMARY KEY (`ID_LISTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORMA DE PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORMA DE PAGAMENTO` (
  `ID` INT NOT NULL,
  `DESCRIÇAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA` (
  `ID_COMPRA` INT NOT NULL AUTO_INCREMENT,
  `CARRINHO_ID_CARRINHO` INT NOT NULL,
  `CARRINHO_CLIENTE_ID_CLIENTE` INT NOT NULL,
  `LISTA DE DESEJOS_ID_LISTA` INT NOT NULL,
  `TOTAL` FLOAT(8,2) NOT NULL,
  `DATA_HORA` DATETIME NOT NULL,
  `FORMA DE PAGAMENTO_ID` INT NOT NULL,
  PRIMARY KEY (`ID_COMPRA`, `CARRINHO_ID_CARRINHO`, `CARRINHO_CLIENTE_ID_CLIENTE`, `LISTA DE DESEJOS_ID_LISTA`, `FORMA DE PAGAMENTO_ID`, `TOTAL`, `DATA_HORA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HISTORICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HISTORICO` (
  `COMPRA_ID_COMPRA` INT NOT NULL,
  `COMPRA_CARRINHO_ID_CARRINHO` INT NOT NULL,
  `COMPRA_CARRINHO_CLIENTE_ID_CLIENTE` INT NOT NULL,
  `COMPRA_LISTA DE DESEJOS_Id_Lista` INT NOT NULL,
  `ID_HITORICO` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  PRIMARY KEY (`ID_HITORICO`, `COMPRA_ID_COMPRA`, `COMPRA_CARRINHO_ID_CARRINHO`, `COMPRA_CARRINHO_CLIENTE_ID_CLIENTE`, `COMPRA_LISTA DE DESEJOS_Id_Lista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_RECL_SUGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_RECL_SUGS` (
  `ID_TIPO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_TIPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RELAMAÇÃO_SUGESTÃO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RELAMAÇÃO_SUGESTÃO` (
  `ID_RECL_SUG` INT NOT NULL AUTO_INCREMENT,
  `DESCRIÇÃO` VARCHAR(450) NOT NULL,
  `DATA_HORA` DATETIME NOT NULL,
  `TIPO_RECL_SUGS_ID_TIPO` INT NOT NULL,
  `USUARIO_CPF_CNPJ` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_RECL_SUG`, `TIPO_RECL_SUGS_ID_TIPO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
